/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

//#import "MMUIButton.h"
#import <UIkit/UIButton.h>
@class WCDataItem;

@interface WCLikeButton : UIButton {
	WCDataItem* m_item;
	unsigned long m_uiSourceType;
	BOOL m_likeOperating;
}
@property(assign, nonatomic) unsigned long m_uiSourceType;
@property(retain, nonatomic) WCDataItem* m_item;
//-(void).cxx_destruct;
-(void)onLikeFriend;
-(void)LikeBtnReduceEnd;
-(void)LikeBtnReduce;
-(void)LikeBtnEnlarge;
-(id)initWithDataItem:(id)dataItem;
-(void)updateLikeBtn;
@end

